# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# test-real-service-e2e pipeline

name: $(Build.BuildId)

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: client   # Name of the pipeline resource
    source: Build - client packages
    branch: main # Default branch for manual/scheduled triggers if none is selected

variables:
- group: prague-key-vault
- name: testWorkspace
  value: $(Pipeline.Workspace)/test
- name: testPackage
  value: "@fluid-private/test-end-to-end-tests"
  readonly: true
- name: absolutePathToTelemetryGenerator
  value: $(Build.SourcesDirectory)/tools/telemetry-generator
  readonly: true

lockBehavior: sequential
stages:

  # end-to-end tests routerlicious
  - stage: e2e_routerlicious
    displayName: e2e - routerlicious
    dependsOn: []
    # use a variable group with exclusive lock force only one run at a time and avoid overloading the server/throttling
    variables:
    - group: e2e-r11s-lock
    jobs:
    - template: templates/include-test-real-service.yml
      parameters:
        poolBuild: Small
        testPackage: ${{ variables.testPackage }}
        testWorkspace: ${{ variables.testWorkspace }}
        artifactBuildId: $(resources.pipeline.client.runID)
        testCommand: test:realsvc:routerlicious:report
        continueOnError: true
        r11sSelfSignedCertSecureFile: wu2-ppe-tls-certificate.pem
        splitTestVariants:
          - name: Non-compat
            flags: --compatVersion=0
          - name: N-1
            flags: --compatVersion=-1
          - name: LTS
            flags: --compatVersion=LTS
          - name: Cross-version
            flags: --compatVersion=CROSS_VERSION
          # Assumes Non-compat and N-1 scenarios are covered
          - name: N-2ToLTS+1-back-compat
            flags: --compatVersion=FULL
        env:
          fluid__test__driver__r11s: $(automation-fluid-test-driver-r11s-ppe)
          FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
